# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 23:55
from __future__ import unicode_literals

from django.db import migrations
from ..forms.crud import *

def populate_records(apps,schema_editor):
	Record = apps.get_model("crudapp","Record")

	records = [
		{"name": "Alde"},
		{"name": "Jeyran"},
		{"name": "Jelord"},
		{"name": "Person2"},
	]

	for record in records:
		record_form = Record_form(record)
		if record_form.is_valid():
			record_form.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(populate_records)
    ]
